<?php

namespace Database\Seeders;

use App\Enums\SettingGroup;
use App\Enums\SettingType;
use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // General Settings
            [
                'key' => 'app.name',
                'value' => 'AirforceBES Events',
                'type' => SettingType::TEXT,
                'group' => SettingGroup::GENERAL,
                'label' => 'Application Name',
                'description' => 'The name of your application',
                'is_required' => true,
                'default_value' => 'AirforceBES Events',
                'sort_order' => 1,
                'is_public' => true,
            ],
            [
                'key' => 'app.description',
                'value' => 'Professional event management system for AirforceBES',
                'type' => SettingType::TEXT,
                'group' => SettingGroup::GENERAL,
                'label' => 'Application Description',
                'description' => 'Brief description of your application',
                'is_required' => false,
                'default_value' => 'Professional event management system for AirforceBES',
                'sort_order' => 2,
                'is_public' => true,
            ],
            [
                'key' => 'app.logo',
                'value' => null,
                'type' => SettingType::FILE,
                'group' => SettingGroup::GENERAL,
                'label' => 'Application Logo',
                'description' => 'Upload your application logo (PNG, JPG, SVG)',
                'is_required' => false,
                'default_value' => null,
                'sort_order' => 3,
                'is_public' => true,
            ],
            [
                'key' => 'app.favicon',
                'value' => null,
                'type' => SettingType::FILE,
                'group' => SettingGroup::GENERAL,
                'label' => 'Favicon',
                'description' => 'Upload your favicon (ICO, PNG)',
                'is_required' => false,
                'default_value' => null,
                'sort_order' => 4,
                'is_public' => true,
            ],
            [
                'key' => 'app.timezone',
                'value' => 'UTC',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::GENERAL,
                'label' => 'Default Timezone',
                'description' => 'Default timezone for the application',
                'options' => [
                    'UTC' => 'UTC',
                    'America/New_York' => 'Eastern Time',
                    'America/Chicago' => 'Central Time',
                    'America/Denver' => 'Mountain Time',
                    'America/Los_Angeles' => 'Pacific Time',
                    'Europe/London' => 'London',
                    'Europe/Paris' => 'Paris',
                    'Asia/Tokyo' => 'Tokyo',
                    'Asia/Shanghai' => 'Shanghai',
                    'Australia/Sydney' => 'Sydney',
                ],
                'is_required' => true,
                'default_value' => 'UTC',
                'sort_order' => 5,
                'is_public' => false,
            ],
            [
                'key' => 'app.date_format',
                'value' => 'M j, Y',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::GENERAL,
                'label' => 'Date Format',
                'description' => 'Default date format for the application',
                'options' => [
                    'M j, Y' => 'Jan 1, 2025',
                    'j M Y' => '1 Jan 2025',
                    'Y-m-d' => '2025-01-01',
                    'd/m/Y' => '01/01/2025',
                    'm/d/Y' => '01/01/2025',
                ],
                'is_required' => true,
                'default_value' => 'M j, Y',
                'sort_order' => 6,
                'is_public' => false,
            ],
            [
                'key' => 'app.time_format',
                'value' => 'g:i A',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::GENERAL,
                'label' => 'Time Format',
                'description' => 'Default time format for the application',
                'options' => [
                    'g:i A' => '9:30 AM',
                    'H:i' => '09:30',
                    'G:i' => '9:30',
                ],
                'is_required' => true,
                'default_value' => 'g:i A',
                'sort_order' => 7,
                'is_public' => false,
            ],
            [
                'key' => 'events.default_capacity',
                'value' => '100',
                'type' => SettingType::INTEGER,
                'group' => SettingGroup::GENERAL,
                'label' => 'Default Event Capacity',
                'description' => 'Default maximum capacity for new events',
                'is_required' => true,
                'default_value' => '100',
                'sort_order' => 8,
                'is_public' => false,
            ],
            [
                'key' => 'events.registration_deadline_days',
                'value' => '7',
                'type' => SettingType::INTEGER,
                'group' => SettingGroup::GENERAL,
                'label' => 'Registration Deadline (Days)',
                'description' => 'Default days before event when registration closes',
                'is_required' => true,
                'default_value' => '7',
                'sort_order' => 9,
                'is_public' => false,
            ],
            [
                'key' => 'app.contact_email',
                'value' => 'admin@airforcebes-events.com',
                'type' => SettingType::EMAIL,
                'group' => SettingGroup::GENERAL,
                'label' => 'Contact Email',
                'description' => 'Primary contact email for the application',
                'is_required' => true,
                'default_value' => 'admin@airforcebes-events.com',
                'sort_order' => 10,
                'is_public' => true,
            ],
            [
                'key' => 'app.contact_phone',
                'value' => '+1-555-0123',
                'type' => SettingType::TEXT,
                'group' => SettingGroup::GENERAL,
                'label' => 'Contact Phone',
                'description' => 'Primary contact phone number',
                'is_required' => false,
                'default_value' => '+1-555-0123',
                'sort_order' => 11,
                'is_public' => true,
            ],
            [
                'key' => 'app.url',
                'value' => 'https://airforcebes-events.test',
                'type' => SettingType::URL,
                'group' => SettingGroup::GENERAL,
                'label' => 'Application URL',
                'description' => 'The public URL of your application',
                'is_required' => true,
                'default_value' => 'https://airforcebes-events.test',
                'sort_order' => 12,
                'is_public' => false,
            ],

            // SMTP Settings
            [
                'key' => 'mail.driver',
                'value' => 'smtp',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::SMTP,
                'label' => 'Mail Driver',
                'description' => 'The mail driver to use for sending emails',
                'options' => [
                    'smtp' => 'SMTP',
                    'sendmail' => 'Sendmail',
                    'mailgun' => 'Mailgun',
                    'ses' => 'Amazon SES',
                    'postmark' => 'Postmark',
                ],
                'is_required' => true,
                'default_value' => 'smtp',
                'sort_order' => 1,
                'is_public' => false,
            ],
            [
                'key' => 'mail.smtp_provider',
                'value' => 'custom',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::SMTP,
                'label' => 'SMTP Provider',
                'description' => 'Select your SMTP provider for auto-configuration',
                'options' => [
                    'gmail' => 'Gmail / Google Workspace',
                    'outlook' => 'Outlook / Office 365',
                    'sendgrid' => 'SendGrid',
                    'mailgun' => 'Mailgun',
                    'ses' => 'Amazon SES',
                    'postmark' => 'Postmark',
                    'custom' => 'Custom SMTP',
                ],
                'is_required' => true,
                'default_value' => 'custom',
                'sort_order' => 2,
                'is_public' => false,
            ],
            [
                'key' => 'mail.smtp_host',
                'value' => '',
                'type' => SettingType::TEXT,
                'group' => SettingGroup::SMTP,
                'label' => 'SMTP Host',
                'description' => 'SMTP server hostname',
                'is_required' => true,
                'default_value' => '',
                'sort_order' => 3,
                'is_public' => false,
            ],
            [
                'key' => 'mail.smtp_port',
                'value' => '587',
                'type' => SettingType::INTEGER,
                'group' => SettingGroup::SMTP,
                'label' => 'SMTP Port',
                'description' => 'SMTP server port',
                'is_required' => true,
                'default_value' => '587',
                'sort_order' => 4,
                'is_public' => false,
            ],
            [
                'key' => 'mail.smtp_username',
                'value' => '',
                'type' => SettingType::TEXT,
                'group' => SettingGroup::SMTP,
                'label' => 'SMTP Username',
                'description' => 'SMTP authentication username',
                'is_required' => false,
                'default_value' => '',
                'sort_order' => 5,
                'is_public' => false,
            ],
            [
                'key' => 'mail.smtp_password',
                'value' => '',
                'type' => SettingType::PASSWORD,
                'group' => SettingGroup::SMTP,
                'label' => 'SMTP Password',
                'description' => 'SMTP authentication password',
                'is_encrypted' => true,
                'is_required' => false,
                'default_value' => '',
                'sort_order' => 6,
                'is_public' => false,
            ],
            [
                'key' => 'mail.smtp_encryption',
                'value' => 'tls',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::SMTP,
                'label' => 'SMTP Encryption',
                'description' => 'SMTP encryption method',
                'options' => [
                    'tls' => 'TLS',
                    'ssl' => 'SSL',
                    'none' => 'None',
                ],
                'is_required' => true,
                'default_value' => 'tls',
                'sort_order' => 7,
                'is_public' => false,
            ],
            [
                'key' => 'mail.from_name',
                'value' => 'AirforceBES Events',
                'type' => SettingType::TEXT,
                'group' => SettingGroup::SMTP,
                'label' => 'Sender Name',
                'description' => 'Default sender name for emails',
                'is_required' => true,
                'default_value' => 'AirforceBES Events',
                'sort_order' => 8,
                'is_public' => false,
            ],
            [
                'key' => 'mail.from_address',
                'value' => 'noreply@airforcebes-events.com',
                'type' => SettingType::EMAIL,
                'group' => SettingGroup::SMTP,
                'label' => 'Sender Email',
                'description' => 'Default sender email address',
                'is_required' => true,
                'default_value' => 'noreply@airforcebes-events.com',
                'sort_order' => 9,
                'is_public' => false,
            ],
            [
                'key' => 'mail.reply_to',
                'value' => 'support@airforcebes-events.com',
                'type' => SettingType::EMAIL,
                'group' => SettingGroup::SMTP,
                'label' => 'Reply To Email',
                'description' => 'Reply-to email address for emails',
                'is_required' => false,
                'default_value' => 'support@airforcebes-events.com',
                'sort_order' => 10,
                'is_public' => false,
            ],
            [
                'key' => 'mail.test_email',
                'value' => '',
                'type' => SettingType::EMAIL,
                'group' => SettingGroup::SMTP,
                'label' => 'Test Email Address',
                'description' => 'Email address for testing SMTP configuration',
                'is_required' => false,
                'default_value' => '',
                'sort_order' => 11,
                'is_public' => false,
            ],

            // Notification Settings
            [
                'key' => 'notifications.enable_emails',
                'value' => true,
                'type' => SettingType::BOOLEAN,
                'group' => SettingGroup::NOTIFICATIONS,
                'label' => 'Enable Email Notifications',
                'description' => 'Enable or disable all email notifications',
                'is_required' => true,
                'default_value' => '1',
                'sort_order' => 1,
                'is_public' => false,
            ],
            [
                'key' => 'notifications.registration_confirmation',
                'value' => true,
                'type' => SettingType::BOOLEAN,
                'group' => SettingGroup::NOTIFICATIONS,
                'label' => 'Registration Confirmation Emails',
                'description' => 'Send confirmation emails when users register for events',
                'is_required' => true,
                'default_value' => '1',
                'sort_order' => 2,
                'is_public' => false,
            ],
            [
                'key' => 'notifications.check_in_notifications',
                'value' => true,
                'type' => SettingType::BOOLEAN,
                'group' => SettingGroup::NOTIFICATIONS,
                'label' => 'Check-in Notifications',
                'description' => 'Send notifications when attendees check in',
                'is_required' => true,
                'default_value' => '1',
                'sort_order' => 3,
                'is_public' => false,
            ],
            [
                'key' => 'notifications.event_reminders',
                'value' => true,
                'type' => SettingType::BOOLEAN,
                'group' => SettingGroup::NOTIFICATIONS,
                'label' => 'Event Reminders',
                'description' => 'Send reminder emails before events',
                'is_required' => true,
                'default_value' => '1',
                'sort_order' => 4,
                'is_public' => false,
            ],
            [
                'key' => 'notifications.admin_notifications',
                'value' => true,
                'type' => SettingType::BOOLEAN,
                'group' => SettingGroup::NOTIFICATIONS,
                'label' => 'Admin Notifications',
                'description' => 'Send notifications to administrators',
                'is_required' => true,
                'default_value' => '1',
                'sort_order' => 5,
                'is_public' => false,
            ],
            [
                'key' => 'notifications.reminder_days_before',
                'value' => '1',
                'type' => SettingType::INTEGER,
                'group' => SettingGroup::NOTIFICATIONS,
                'label' => 'Reminder Days Before Event',
                'description' => 'Number of days before event to send reminder',
                'is_required' => true,
                'default_value' => '1',
                'sort_order' => 6,
                'is_public' => false,
            ],

            // Appearance Settings
            [
                'key' => 'appearance.primary_color',
                'value' => '#667eea',
                'type' => SettingType::COLOR,
                'group' => SettingGroup::APPEARANCE,
                'label' => 'Primary Color',
                'description' => 'Primary brand color for the application',
                'is_required' => true,
                'default_value' => '#667eea',
                'sort_order' => 1,
                'is_public' => true,
            ],
            [
                'key' => 'appearance.secondary_color',
                'value' => '#764ba2',
                'type' => SettingType::COLOR,
                'group' => SettingGroup::APPEARANCE,
                'label' => 'Secondary Color',
                'description' => 'Secondary brand color for the application',
                'is_required' => true,
                'default_value' => '#764ba2',
                'sort_order' => 2,
                'is_public' => true,
            ],
            [
                'key' => 'appearance.theme',
                'value' => 'light',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::APPEARANCE,
                'label' => 'Theme',
                'description' => 'Application theme preference',
                'options' => [
                    'light' => 'Light',
                    'dark' => 'Dark',
                    'auto' => 'Auto (System)',
                ],
                'is_required' => true,
                'default_value' => 'light',
                'sort_order' => 3,
                'is_public' => true,
            ],
            [
                'key' => 'appearance.custom_css',
                'value' => '',
                'type' => SettingType::TEXT,
                'group' => SettingGroup::APPEARANCE,
                'label' => 'Custom CSS',
                'description' => 'Custom CSS to override default styles',
                'is_required' => false,
                'default_value' => '',
                'sort_order' => 4,
                'is_public' => false,
            ],
            [
                'key' => 'appearance.footer_text',
                'value' => '© 2025 AirforceBES Events. All rights reserved.',
                'type' => SettingType::TEXT,
                'group' => SettingGroup::APPEARANCE,
                'label' => 'Footer Text',
                'description' => 'Custom footer text',
                'is_required' => false,
                'default_value' => '© 2025 AirforceBES Events. All rights reserved.',
                'sort_order' => 5,
                'is_public' => true,
            ],

            // System Settings
            [
                'key' => 'system.enable_registrations',
                'value' => true,
                'type' => SettingType::BOOLEAN,
                'group' => SettingGroup::SYSTEM,
                'label' => 'Enable Registrations',
                'description' => 'Enable or disable event registrations globally',
                'is_required' => true,
                'default_value' => '1',
                'sort_order' => 1,
                'is_public' => false,
            ],
            [
                'key' => 'system.maintenance_mode',
                'value' => false,
                'type' => SettingType::BOOLEAN,
                'group' => SettingGroup::SYSTEM,
                'label' => 'Maintenance Mode',
                'description' => 'Enable maintenance mode (admin access only)',
                'is_required' => true,
                'default_value' => '0',
                'sort_order' => 2,
                'is_public' => false,
            ],
            [
                'key' => 'system.debug_mode',
                'value' => false,
                'type' => SettingType::BOOLEAN,
                'group' => SettingGroup::SYSTEM,
                'label' => 'Debug Mode',
                'description' => 'Enable debug mode (development only)',
                'is_required' => true,
                'default_value' => '0',
                'sort_order' => 3,
                'is_public' => false,
            ],
            [
                'key' => 'system.session_timeout',
                'value' => '120',
                'type' => SettingType::INTEGER,
                'group' => SettingGroup::SYSTEM,
                'label' => 'Session Timeout (Minutes)',
                'description' => 'User session timeout in minutes',
                'is_required' => true,
                'default_value' => '120',
                'sort_order' => 4,
                'is_public' => false,
            ],
            [
                'key' => 'system.max_file_upload_size',
                'value' => '2048',
                'type' => SettingType::INTEGER,
                'group' => SettingGroup::SYSTEM,
                'label' => 'Max File Upload Size (KB)',
                'description' => 'Maximum file upload size in kilobytes',
                'is_required' => true,
                'default_value' => '2048',
                'sort_order' => 5,
                'is_public' => false,
            ],
            [
                'key' => 'system.allowed_file_types',
                'value' => 'jpg,jpeg,png,gif,pdf,doc,docx',
                'type' => SettingType::TEXT,
                'group' => SettingGroup::SYSTEM,
                'label' => 'Allowed File Types',
                'description' => 'Comma-separated list of allowed file extensions',
                'is_required' => true,
                'default_value' => 'jpg,jpeg,png,gif,pdf,doc,docx',
                'sort_order' => 6,
                'is_public' => false,
            ],

            // Email Template Settings
            [
                'key' => 'email_templates.registration_confirmation_subject',
                'value' => 'Event Registration Confirmation - {{event_title}}',
                'type' => SettingType::TEXT,
                'group' => SettingGroup::EMAIL_TEMPLATES,
                'label' => 'Registration Confirmation Subject',
                'description' => 'Subject line for registration confirmation emails',
                'is_required' => true,
                'default_value' => 'Event Registration Confirmation - {{event_title}}',
                'sort_order' => 1,
                'is_public' => false,
            ],
            [
                'key' => 'email_templates.registration_confirmation_body',
                'value' => $this->getDefaultRegistrationTemplate(),
                'type' => SettingType::TEXT,
                'group' => SettingGroup::EMAIL_TEMPLATES,
                'label' => 'Registration Confirmation Body',
                'description' => 'Body content for registration confirmation emails',
                'is_required' => true,
                'default_value' => $this->getDefaultRegistrationTemplate(),
                'sort_order' => 2,
                'is_public' => false,
            ],
            [
                'key' => 'email_templates.event_reminder_subject',
                'value' => 'Event Reminder - {{event_title}} Tomorrow',
                'type' => SettingType::TEXT,
                'group' => SettingGroup::EMAIL_TEMPLATES,
                'label' => 'Event Reminder Subject',
                'description' => 'Subject line for event reminder emails',
                'is_required' => true,
                'default_value' => 'Event Reminder - {{event_title}} Tomorrow',
                'sort_order' => 3,
                'is_public' => false,
            ],
            [
                'key' => 'email_templates.event_reminder_body',
                'value' => $this->getDefaultReminderTemplate(),
                'type' => SettingType::TEXT,
                'group' => SettingGroup::EMAIL_TEMPLATES,
                'label' => 'Event Reminder Body',
                'description' => 'Body content for event reminder emails',
                'is_required' => true,
                'default_value' => $this->getDefaultReminderTemplate(),
                'sort_order' => 4,
                'is_public' => false,
            ],
        ];

        foreach ($settings as $settingData) {
            Setting::updateOrCreate(
                ['key' => $settingData['key']],
                $settingData
            );
        }
    }

    /**
     * Get default registration confirmation email template
     */
    private function getDefaultRegistrationTemplate(): string
    {
        return "Dear {{attendee_name}},

Thank you for registering for {{event_title}}!

Event Details:
- Date: {{event_date}}
- Time: {{event_time}}
- Venue: {{event_venue}}
- Registration Code: {{registration_code}}

Please bring this registration code or the QR code to the event for check-in.

If you have any questions, please contact us at {{contact_email}}.

Best regards,
{{app_name}} Team";
    }

    /**
     * Get default event reminder email template
     */
    private function getDefaultReminderTemplate(): string
    {
        return "Dear {{attendee_name}},

This is a friendly reminder that {{event_title}} is tomorrow!

Event Details:
- Date: {{event_date}}
- Time: {{event_time}}
- Venue: {{event_venue}}
- Registration Code: {{registration_code}}

Please don't forget to bring your registration code or QR code for check-in.

We look forward to seeing you!

Best regards,
{{app_name}} Team";
    }
}
